services:

  server:
    build:
      context: ./server
    container_name: pqc-server
    hostname: server
    networks:
      - pqc-net
    volumes:
      - ./keys/authorized_keys:/tmp/authorized_keys:ro
    ports:
      - "2222:22"
    restart: unless-stopped

  client:
    build:
      context: ./client
    container_name: pqc-client
    hostname: client
    networks:
      - pqc-net
    volumes:
      - ./keys/id_ed25519:/home/researcher/.ssh/id_ed25519:ro
      - ./keys/id_ed25519.pub:/home/researcher/.ssh/id_ed25519.pub:ro
    depends_on:
      - server
    stdin_open: true
    tty: true
    restart: unless-stopped


networks:
  pqc-net:
    driver: bridge
